from json.encoder import JSONEncoder
from typing import Any, NoReturn, Iterator, Callable


def es6_format(value: str) -> str: ...
def default(self, o: Any) -> NoReturn: ...


_iterencode: Callable[[Any, int], Iterator[Any]]


class Encoder(JSONEncoder):
    skipkeys: bool = ...
    ensure_ascii: bool = ...
    check_circular: bool = ...
    allow_nan: bool = ...
    indent: Any = ...
    item_separator: str = ...
    key_separator: str = ...
    def __init__(self) -> None: ...

    @classmethod
    def encode(cls, o: Any) -> str: ...


_encode: Callable[[Any], str]


def canonicalize(obj: Any, utf8: bool) -> str: ...
